name = "fm-link-sharing"
compatibility_date = "2023-01-01"
compatibility_flags = ["nodejs_compat"]

[[ d1_databases ]]
binding = "DB"
database_name = "fm_link_sharing"
database_id = "35ec0f36-c359-43f5-ae94-f45d52f35a4f"
